const actions = {
  REQUEST_HELLO_WORLD: "REQUEST_HELLO_WORLD",
  RECEIVE_HELLO_WORLD: "RECEIVE_HELLO_WORLD",
  SELECT_VESSEL: "SELECT_VESSEL",
  ADD_CONTAINER: "ADD_CONTAINER",
  UPDATE_POSSIBILITY: "UPDATE_POSSIBILITY",
};

export default actions;
